---
- hosts: all
  become: yes
  vars:
    NODEJS_VERSION: "node_14.x"
    ansible_distribution_release: "focal"

  tasks:
    - name: Install gpg key for NodeJS repo
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Add NodeJS repo
      apt_repository:
        repo: "deb https://deb.nodesource.com/{{ NODEJS_VERSION }} {{ ansible_distribution_release }} main"
        state: present

    - name: Install the NodeJS
      apt:
        update_cache: yes
        name: nodejs
        state: present