---
- hosts: all
  become: yes
  vars:
    NODEJS_VERSION: "14"

  tasks:
    - name: Install gpg key for NodeJS repo
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Add NodeJS repo
    apt_repository:
      repo: "deb https://deb.nodesource.com/setup_{{ NODEJS_VERSION }}.x"
      state: present
      update_cache: yes

    - name: Install the node.js
      apt:
        name: nodejs
        state: present